### ISSUE TITLE
KeyError: 'quarterhourly' 

### ISSUE THREAD

**Issue by Neled77** [elden1337/hass-peaq#232]
Hey Elden,

latest version on boot:

```
2023-03-28 19:32:59.477 WARNING (MainThread) [peaqevcore.models.hub.chargerswitch] Chargerobject state was None while getting cu
rrent. Updatecurrent will still process but you may see a missmatch in frontend.                                                
2023-03-28 19:33:00.385 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved                  
Traceback (most recent call last):                                                                                              
  File "/config/custom_components/peaqev/sensor.py", line 67, in _gather_utility_sensors                                        
    ret.append(PeaqUtilitySensor(hub, i, hub.sensors.locale.data.peak_cycle, METER_OFFSET, config.entry_id, hass))              
  File "/config/custom_components/peaqev/sensors/utility_sensor.py", line 67, in __init__                                       
    super().__init__(                                                                                                           
  File "/usr/lib/python3.10/site-packages/homeassistant/components/utility_meter/sensor.py", line 339, in __init__              
    self._cron_pattern = PERIOD2CRON[meter_type].format(                                                                        
KeyError: 'quarterhourly'                                                                                                       
^[c2023-03-28 19:33:09.037 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform nordpool is taking ov
er 10 seconds.                 
```                                        

All the best

Neled

**Comment by elden1337** [comment]
If you want to have it working tonight, change hub.sensors.locale.data.peak_cycle to "quarter-hourly" in that file. @Neled77
