### ISSUE TITLE
Missing entities

### ISSUE THREAD

**Issue by kirilldem** [elden1337/hass-peaq#248]
I have reinstalled peaqev (peaqev and HA on latest versions) and now I am getting errors with regards to seeing my nordpool, power meter or easee integration. 

I know that the rewrite has improved startup times, but perhaps it is too fast now ;) Rebooted 3 times - 2 times peaqev is unavailable, like this:
![image](https://user-images.githubusercontent.com/44521162/231128957-7233f716-ad8a-43c6-9e4d-4bd70b849dd2.png)
errors in the logfiles:

```
Logger: custom_components.peaqev.peaqservice.chargertypes.entitieshelper
Source: custom_components/peaqev/peaqservice/chargertypes/entitieshelper.py:59
Integration: peaqev ev-charging ([documentation](https://github.com/elden1337/hass-peaq), [issues](https://github.com/elden1337/hass-peaq/issues))
First occurred: 12:04:20 PM (1 occurrences)
Last logged: 12:04:20 PM

no entities found for easee at 1681207460.2255073

```

```
Logger: homeassistant.config_entries
Source: custom_components/peaqev/peaqservice/hub/sensors/ihub_sensors.py:95
Integration: peaqev ev-charging ([documentation](https://github.com/elden1337/hass-peaq), [issues](https://github.com/elden1337/hass-peaq/issues))
First occurred: 12:04:20 PM (1 occurrences)
Last logged: 12:04:20 PM

Error setting up entry sensor.house_power_consumption for peaqev
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/peaqev/__init__.py", line 30, in async_setup_entry
    await hub.setup()
  File "/config/custom_components/peaqev/peaqservice/hub/hub.py", line 82, in setup
    self.sensors: IHubSensors = await HubSensorsFactory.async_create(hub=self)  # top level
  File "/config/custom_components/peaqev/peaqservice/hub/factories/hubsensors_factory.py", line 22, in async_create
    return await HubSensorsFactory.async_setup(hub, sensors())
  File "/config/custom_components/peaqev/peaqservice/hub/factories/hubsensors_factory.py", line 26, in async_setup
    await sensors.async_setup(
  File "/config/custom_components/peaqev/peaqservice/hub/sensors/hub_sensors.py", line 18, in async_setup
    await super().async_setup_base(
  File "/config/custom_components/peaqev/peaqservice/hub/sensors/ihub_sensors.py", line 95, in async_setup_base
    listenerentity=self.chargertype.entities.powermeter,
AttributeError: type object 'ChargerEntitiesModel' has no attribute 'powermeter'
```

Load time for peaqev is 0,03s
ESPHome (power meter):  2,79s
Easee: 2,29s

This behaviour is consistent with "Restart" or "Reboot" of home assistant.

The integration worked once it was installed and rebooted the first time.

**Comment by elden1337** [comment]
Happens from time to time here as well. I wonder if the "after-dependencies" clause is broken in ha 2023.4. Peaqev shouldnt even start before these integrations are loaded. 

But will ofc see if i can do something.

**Comment by elden1337** [comment]
hopefully works better now @kirilldem 
https://github.com/elden1337/hass-peaq/releases/tag/v2.9.1

interim fix. i probably have to re-write more to listen to events or something, but wanted to push it out to hopefully work a bit better now.

**Comment by kirilldem** [comment]
It works again with the hotfix. Thank you

**Comment by kirilldem** [comment]
New errors now though :( 

A restart hasn't helped:
```

Logger: custom_components.peaqev.peaqservice.hub.hub
Source: custom_components/peaqev/peaqservice/hub/hub.py:156
Integration: peaqev ev-charging ([documentation](https://github.com/elden1337/hass-peaq), [issues](https://github.com/elden1337/hass-peaq/issues))
First occurred: 10:12:10 PM (11210 occurrences)
Last logged: 11:21:39 PM

Unable to handle data-update: sensor.house_power_consumption <state sensor.house_power_consumption=2927; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-11T23:21:36.537685+02:00>|<state sensor.house_power_consumption=2951; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-11T23:21:38.272966+02:00>. Exception: 'RegularHours' object has no attribute '_scheduler'
Unable to handle data-update: sensor.peaqev_energy_including_car_hourly <state sensor.peaqev_energy_including_car_hourly=0.80; state_class=total, source=sensor.peaqev_energy_including_car, status=collecting, last_period=3.22, last_valid_state=1327.11, meter_period=hourly, cron pattern=0 * * * *, last_reset=2023-04-11T21:00:00.013343+00:00, unit_of_measurement=kWh, device_class=energy, icon=mdi:counter, friendly_name=Peaqev energy_including_car hourly @ 2023-04-11T23:21:25.169267+02:00>|<state sensor.peaqev_energy_including_car_hourly=0.81; state_class=total, source=sensor.peaqev_energy_including_car, status=collecting, last_period=3.22, last_valid_state=1327.12, meter_period=hourly, cron pattern=0 * * * *, last_reset=2023-04-11T21:00:00.013343+00:00, unit_of_measurement=kWh, device_class=energy, icon=mdi:counter, friendly_name=Peaqev energy_including_car hourly @ 2023-04-11T23:21:38.277126+02:00>. Exception: 'RegularHours' object has no attribute '_scheduler'
Unable to handle data-update: sensor.house_power_consumption <state sensor.house_power_consumption=2951; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-11T23:21:38.272966+02:00>|<state sensor.house_power_consumption=2927; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-11T23:21:38.380853+02:00>. Exception: 'RegularHours' object has no attribute '_scheduler'
Unable to handle data-update: sensor.house_power_consumption <state sensor.house_power_consumption=2927; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-11T23:21:38.380853+02:00>|<state sensor.house_power_consumption=1463; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-11T23:21:39.632431+02:00>. Exception: 'RegularHours' object has no attribute '_scheduler'
Unable to handle data-update: sensor.house_power_consumption <state sensor.house_power_consumption=1463; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-11T23:21:39.632431+02:00>|<state sensor.house_power_consumption=2927; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-11T23:21:39.755102+02:00>. Exception: 'RegularHours' object has no attribute '_scheduler'
```

```
Logger: homeassistant.helpers.entity
Source: custom_components/peaqev/peaqservice/hub/hub.py:248
Integration: peaqev ev-charging ([documentation](https://github.com/elden1337/hass-peaq), [issues](https://github.com/elden1337/hass-peaq/issues))
First occurred: 10:12:14 PM (1042 occurrences)
Last logged: 11:21:41 PM

Update for sensor.peaqev_charger_controller fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/config/custom_components/peaqev/sensors/peaq_sensor.py", line 47, in async_update
    ret = await self.hub.async_request_sensor_data(
  File "/config/custom_components/peaqev/peaqservice/hub/hub.py", line 248, in async_request_sensor_data
    "is_scheduler_active": getattr(self.hours.scheduler, "scheduler_active"),
  File "/usr/local/lib/python3.10/site-packages/peaqevcore/services/hourselection/initializers/hoursbase.py", line 41, in scheduler
    return self._scheduler
AttributeError: 'RegularHours' object has no attribute '_scheduler'
```

**Comment by elden1337** [comment]
Yes you posted that yesterday ;). I made #249 from that comment. Im done with that so i will release 2.9.2 in a couple of moments.

**Comment by kirilldem** [comment]
After amending the line to:

`            "is_scheduler_active": getattr(self.hours.scheduler, "scheduler_active", False),`


```
Logger: homeassistant.helpers.entity
Source: custom_components/peaqev/peaqservice/hub/hub.py:242
Integration: peaqev ev-charging ([documentation](https://github.com/elden1337/hass-peaq), [issues](https://github.com/elden1337/hass-peaq/issues))
First occurred: 10:10:15 AM (176 occurrences)
Last logged: 10:21:56 AM

Update for sensor.peaqev_charger_controller fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/config/custom_components/peaqev/sensors/peaq_sensor.py", line 47, in async_update
    ret = await self.hub.async_request_sensor_data(
  File "/config/custom_components/peaqev/peaqservice/hub/hub.py", line 242, in async_request_sensor_data
    "is_scheduler_active": getattr(self.hours.scheduler, "scheduler_active", False),
  File "/usr/local/lib/python3.10/site-packages/peaqevcore/services/hourselection/initializers/hoursbase.py", line 41, in scheduler
    return self._scheduler
AttributeError: 'RegularHours' object has no attribute '_scheduler'
```

and
```

Logger: custom_components.peaqev.peaqservice.hub.hub
Source: custom_components/peaqev/peaqservice/hub/hub.py:150
Integration: peaqev ev-charging ([documentation](https://github.com/elden1337/hass-peaq), [issues](https://github.com/elden1337/hass-peaq/issues))
First occurred: 10:09:40 AM (1456 occurrences)
Last logged: 10:21:56 AM

Unable to handle data-update: sensor.house_power_consumption <state sensor.house_power_consumption=659; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-12T10:21:54.568559+02:00>|<state sensor.house_power_consumption=669; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-12T10:21:55.110775+02:00>. Exception: 'RegularHours' object has no attribute '_scheduler'
Unable to handle data-update: sensor.house_power_consumption <state sensor.house_power_consumption=669; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-12T10:21:55.110775+02:00>|<state sensor.house_power_consumption=667; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-12T10:21:55.646221+02:00>. Exception: 'RegularHours' object has no attribute '_scheduler'
Unable to handle data-update: sensor.peaqev_average_consumption <state sensor.peaqev_average_consumption=903; entity_id=sensor.peaqev_house_power, unit_of_measurement=W, device_class=power, icon=mdi:home-lightning-bolt, friendly_name=Peaqev Average consumption @ 2023-04-12T10:21:44.163317+02:00>|<state sensor.peaqev_average_consumption=899; entity_id=sensor.peaqev_house_power, unit_of_measurement=W, device_class=power, icon=mdi:home-lightning-bolt, friendly_name=Peaqev Average consumption @ 2023-04-12T10:21:56.166144+02:00>. Exception: 'RegularHours' object has no attribute '_scheduler'
Unable to handle data-update: sensor.house_power_consumption <state sensor.house_power_consumption=667; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-12T10:21:55.646221+02:00>|<state sensor.house_power_consumption=665; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-12T10:21:56.187139+02:00>. Exception: 'RegularHours' object has no attribute '_scheduler'
Unable to handle data-update: sensor.house_power_consumption <state sensor.house_power_consumption=665; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-12T10:21:56.187139+02:00>|<state sensor.house_power_consumption=662; state_class=measurement, unit_of_measurement=W, device_class=power, icon=mdi:flash-outline, friendly_name=House - Power Consumption @ 2023-04-12T10:21:56.743975+02:00>. Exception: 'RegularHours' object has no attribute '_scheduler'
```
