### ISSUE TITLE
Unexpected exception importing component custom_components.peaqev

### ISSUE THREAD

**Issue by trikkssitt** [elden1337/hass-peaq#268]
Updating to version 2023.06.1 failed to load peaqev.

Unexpected exception importing component custom_components.peaqev
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/peaqev/__init__.py", line 10, in <module>
    from custom_components.peaqev.peaqservice.hub.hub import HomeAssistantHub
  File "/config/custom_components/peaqev/peaqservice/hub/hub.py", line 24, in <module>
    from custom_components.peaqev.peaqservice.hub.factories.hourselection_factory import \
  File "/config/custom_components/peaqev/peaqservice/hub/factories/hourselection_factory.py", line 1, in <module>
    from peaqevcore.services.hourselection.initializers.price_aware_hours import \
  File "/usr/local/lib/python3.11/site-packages/peaqevcore/services/hourselection/initializers/price_aware_hours.py", line 4, in <module>
    from ..hoursselection import Hoursselection as core_hours
  File "/usr/local/lib/python3.11/site-packages/peaqevcore/services/hourselection/hoursselection.py", line 4, in <module>
    from ...models.hourselection.hourselection_model import HourSelectionModel
  File "/usr/local/lib/python3.11/site-packages/peaqevcore/models/hourselection/hourselection_model.py", line 10, in <module>
    @dataclass(frozen=False)
     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1213, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'peaqevcore.models.hourselection.hours_model.HoursModel'> for field hours is not allowed: use default_factory

**Comment by elden1337** [comment]
Oopsy daisy. Ill have a look as soon as possible!

**Comment by elden1337** [comment]
fixed in [2.11.2](https://github.com/elden1337/hass-peaq/releases/tag/v2.11.2) @trikkssitt
