### ISSUE TITLE
Future hours not updated in 3.0

### ISSUE THREAD

**Issue by elden1337** [elden1337/hass-peaq#276]
![image](https://github.com/elden1337/hass-peaq/assets/22585518/c8d1fc7f-2eff-4b85-a1a0-a904b726e3e2)

**Comment by elden1337** [comment]
’’’

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/peaqev/peaqservice/hub/hub.py:283 
Integration: peaqev ev-charging (documentation, issues) 
First occurred: 07:00:02 (2433 occurrences) 
Last logged: 09:42:32

Update for sensor.peaqev_hour_controller fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 695, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 940, in async_device_update
    await self.async_update()
  File "/config/custom_components/peaqev/sensors/money_sensor.py", line 48, in async_update
    ret = await self.hub.async_request_sensor_data(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/peaqev/peaqservice/hub/hub.py", line 283, in async_request_sensor_data
    ret[arg] = await func()
               ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peaqevcore/services/hourselection/initializers/price_aware_hours.py", line 115, in async_get_average_kwh_price
    return await self._core.async_get_average_kwh_price()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peaqevcore/services/hourselection/hoursselection.py", line 96, in async_get_average_kwh_price
    ret_dynamic = self.service.max_min.average_price
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peaqevcore/services/hoursselection_service_new/max_min_charge.py", line 27, in average_price
    return self.model.caluclate_average_price(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/peaqevcore/services/hoursselection_service_new/models/max_min_model.py", line 21, in caluclate_average_price
    first = mean(
            ^^^^^
  File "/usr/local/lib/python3.11/statistics.py", line 432, in mean
    raise StatisticsError('mean requires at least one data point')
statistics.StatisticsError: mean requires at least one data point

’’’
