### ISSUE TITLE
Garo

### ISSUE THREAD

**Issue by elden1337** [elden1337/hass-peaq#7]

**Comment by elden1337** [comment]
https://github.com/sockless-coding/garo_wallbox/tree/master/custom_components/garo_wallbox

**Comment by stejo388** [comment]
Hi, just wondering about the status regarding the GARO integration?

**Comment by elden1337** [comment]
Hi! 
I havent heard from anyone trying to set it up (i dont have one myself so have to rely on others). 
Did you attempt to install it?

**Comment by joek-makewave** [comment]
Hi there,
  I have the Garo wallbox (model GLBDCWM-T222WO). I saw that support for it has been added in a recent release of hass-peaq and tried an install using the main branch.

I quickly found some errors in garowallbox.py regarding entity names that was easy to correct. That got rid of some errors at start-up. The first problem in the log is now:

```
2023-05-25 23:40:08.078 WARNING (MainThread) [custom_components.peaqev.peaqservice.chargertypes.types.garowallbox] You are initiating GaroWallbox as Chargertype. Bare in mind that this chargertype has not been signed off in testing and may be very unstable. Report findings to the developer.
<peaqevcore.services.locale.Locale.LocaleData object at 0x11bdf84f0>
[]
2023-05-25 23:40:08.449 ERROR (MainThread) [homeassistant.components.filter.sensor] Could not convert state:  (<class 'str'>) to number
2023-05-25 23:40:08.451 ERROR (MainThread) [homeassistant.components.filter.sensor] Could not convert state:  (<class 'str'>) to number
```
A bit later I have:
```
2023-05-25 23:40:12.390 WARNING (MainThread) [peaqevcore.models.hub.chargerswitch] Chargerobject state was None while getting current. Updatecurrent will still process but you may see a missmatch in frontend.
2023-05-25 23:41:07.956 ERROR (MainThread) [homeassistant.helpers.event] Error while processing state change for sensor.peaqev_energy_including_car
Traceback (most recent call last):
  File "/Users/jonas/git/hass-peaq/venv/lib/python3.10/site-packages/homeassistant/helpers/event.py", line 288, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/Users/jonas/git/hass-peaq/venv/lib/python3.10/site-packages/homeassistant/core.py", line 577, in async_run_hass_job
    hassjob.target(*args)
  File "/Users/jonas/git/hass-peaq/venv/lib/python3.10/site-packages/homeassistant/components/utility_meter/sensor.py", line 366, in async_reading
    for sensor in self.hass.data[DATA_UTILITY][self._parent_meter][
KeyError: 'utility_meter_data'```

And the state for sensor "Peaqev Charger controller" goes from Stop to Error.

I'm interested in continuing with this. What do you think is the best way to proceed?

**Comment by elden1337** [comment]
Great, yeah I need testers for Garo ;). 

Ill have a look and get back with how to proceed!

**Comment by elden1337** [comment]
2023-05-25 23:40:08.449 ERROR (MainThread) [homeassistant.components.filter.sensor] Could not convert state:  (<class 'str'>) to number

This particular log I think is unrelated to Garo. What do you use as power meter sensor? I don't think i'm floatparsing before putting it into the average-sensors. So i'll double check that.

**Comment by elden1337** [comment]
Which ones of all sensors for peaqev are unavailable for you after boot?

**Comment by elden1337** [comment]
@joek-makewave are these garo-states actually written in caps, or are they lower-case?

```python
    def _set_charger_states(self) -> None:
        self.chargerstates[ChargeControllerStates.Idle] = ["NOT_CONNECTED"]
        self.chargerstates[ChargeControllerStates.Connected] = [
            "CONNECTED",
            "CHARGING_PAUSED",
            "CHARGING_CANCELLED",
        ]
        self.chargerstates[ChargeControllerStates.Done] = ["CHARGING_FINISHED"]
        self.chargerstates[ChargeControllerStates.Charging] = ["CHARGING"]
```

**Comment by joek-makewave** [comment]
> @joek-makewave are these garo-states actually written in caps, or are they lower-case?
> 
> ```python
>     def _set_charger_states(self) -> None:
>         self.chargerstates[ChargeControllerStates.Idle] = ["NOT_CONNECTED"]
>         self.chargerstates[ChargeControllerStates.Connected] = [
>             "CONNECTED",
>             "CHARGING_PAUSED",
>             "CHARGING_CANCELLED",
>         ]
>         self.chargerstates[ChargeControllerStates.Done] = ["CHARGING_FINISHED"]
>         self.chargerstates[ChargeControllerStates.Charging] = ["CHARGING"]
> ```

They are in lower case.
"Vehicle not connected"
"Vehicle connected"
"Charging paused"
"Charging cancelled"
"Charging finished"
"Charging"

**Comment by joek-makewave** [comment]
> 



> 2023-05-25 23:40:08.449 ERROR (MainThread) [homeassistant.components.filter.sensor] Could not convert state: (<class 'str'>) to number
> 
> This particular log I think is unrelated to Garo. What do you use as power meter sensor? I don't think i'm floatparsing before putting it into the average-sensors. So i'll double check that.

OK. I use the load balancer of the Garo wallbox. The power sensor seems to be ok. It works as expected in other places. But I think I might have spotted an error in the Garo wallbox integration. It looks like some of the sensors in the garo wallbox integration with string state cast to int in `native_value`.

**Comment by joek-makewave** [comment]
> Which ones of all sensors for peaqev are unavailable for you after boot?

![image](https://github.com/elden1337/hass-peaq/assets/18322661/bd576b52-b7df-4d90-9395-86f795043135)

**Comment by joek-makewave** [comment]
I made a pull request with the changes I did for the sensor names. There is also a fix for the values of the set mode service call.
